# Generated by Django 5.0 on 2023-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Enter the content here.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter the title.', max_length=200),
        ),
    ]
